# -*- coding: utf-8 -*-
"""豆包预测社交回避Doubao-1.5-thinking-pro（耗时）.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewd4YAXM-BoFsXiavx4ig5t0UGrEYPAo
"""

import os
import json
import time
import requests
from datetime import datetime

# 加载env环境文件
!pip install python-dotenv

# 加载env环境文件
!pip install python-dotenv

# 环境SDK的安装
!pip install volcengine-python-sdk
!pip install volcengine-python-sdk

pip install --upgrade "openai>=1.0"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat > /content/api_key.env << 'EOF'
# OPENAI_API_KEY=2a1b4038-064d-4e37-8d2c-902bc56c8f59
# EOF
#

import os
from openai import OpenAI

# 请确保您已将 API Key 存储在环境变量 ARK_API_KEY 中
# 初始化Openai客户端，从环境变量中读取您的API Key
client = OpenAI(
    # 此为默认路径，您可根据业务所在地域进行配置
    base_url="",
    # 从环境变量中获取您的 API Key
    api_key=os.environ.get("9"),
)

# Non-streaming:
print("----- standard request -----")
completion = client.chat.completions.create(
    # 指定您创建的方舟推理接入点 ID，此处已帮您修改为您的推理接入点 ID
    model="ep-20250517194034-vnwrd",
    messages=[
        {
            "role": "system",
            "content": "你是一个心理学评分专家，善于依据评分标准进行任务的评分"
        },
        {
            "role": "user",
            "content": """异性社交评分回避标准如下：
1 有理由、有点厌恶
2 厌恶所有
3 有理由且厌恶
4 有生理反应
5 极端
请你根据评分标准对以下的内容进行评分（只要一个数字）:
#河北一女子被前夫砍伤进ICU#每天一个恐男恐婚小新闻罢了"""
        }
    ],
    stream=False
)
print(completion.choices[0].message.content)

# 4. 读取微博帖子文件
import pandas as pd

INPUT_PATH = "/content/weibo_600.csv"      # 上传后在 Colab 的路径
OUTPUT_PATH = "/content/weibo_600_scored.csv"

# 尝试用 gb18030 读取（兼容 GBK，也能读到中文）
df = pd.read_csv(INPUT_PATH, encoding="gb18030")
print(f"✅ 已使用 gb18030 编码读取，共 {len(df)} 条")
print("列名：", df.columns.tolist())
df.head()

# 5. 批量调用模型进行评分
scores = []
total = len(df)

for i, text in enumerate(df["weibo_text"], 1):
    resp = client.chat.completions.create(
        model="ep-20250517194034-vnwrd",
        temperature=0,
        max_tokens=1,
        stream=False,
        messages=[
            {"role": "system", "content": "你是心理学评分专家。只返回一个数字分值，不要任何解释。"},
            {"role": "user", "content": (
                "异性社交评分回避标准如下：\n"
                "1 有理由、有点厌恶\n"
                "2 厌恶所有\n"
                "3 有理由且厌恶\n"
                "4 有生理反应\n"
                "5 极端\n"
                f"请根据标准给出下面微博帖子的分值（只要数字）：\n{text}"
            )}
        ]
    )
    score = resp.choices[0].message.content.strip()
    scores.append(score)
    if i % 50 == 0 or i == total:
        print(f"[{i}/{total}] 完成评分，当前示例分数：{score}")

# 合并结果并保存
df["score"] = scores
df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8")
print(f"✅ 全部评分完成，结果已保存到 {OUTPUT_PATH}")

# 批量评分并显示进度
from tqdm.notebook import tqdm

scores = []
MODEL_ID = "ep-20250517194034-vnwrd"
for text in tqdm(df["weibo_text"], desc="评分进度", unit="条"):
    resp = client.chat.completions.create(
        model="ep-20250517194034-vnwrd",
        temperature=0,
        max_tokens=1,
        stream=False,
        messages=[
            {"role": "system", "content": "你是心理学评分专家。只返回一个数字分值，不要任何解释。"},
            {"role": "user", "content": (
                "异性社交评分回避标准如下：\n"
                "1 有理由、有点厌恶\n"
                "2 厌恶所有\n"
                "3 有理由且厌恶\n"
                "4 有生理反应\n"
                "5 极端\n"
                f"请根据标准给出下面微博帖子的分值（只要数字）：\n{text}"
            )}
        ]
    )
    scores.append(resp.choices[0].message.content.strip())

# 合并结果并保存
df["score"] = scores
df.to_csv("weibo_600_scored.csv", index=False, encoding="utf-8")

print("✅ 批量评分完成，结果已保存到 weibo_600_scored.csv")