# -*- coding: utf-8 -*-
"""fine_tuning_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFapLIt9O6Y5QuzT2AUxr7UrUWdeAO9U
"""

!pip install transformers datasets evaluate

from transformers import AutoModelForSequenceClassification, AutoTokenizer, DataCollatorWithPadding, Trainer, TrainingArguments
from datasets import load_dataset

import torch

import evaluate
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
device

from datasets import load_dataset

# 导入数据（指定编码）
data_files = {
    "train": "/content/drive/MyDrive/社交回避/part.csv"
}

dataset_reloaded = load_dataset(
    "csv",
    data_files=data_files,
    encoding="gb18030"   # ✅ 解决 UnicodeDecodeError 的关键
    # 如果你确定是 gbk，也可以换成 encoding="gbk"
)

# 分割数据
# 先将dataset按70%比例分割为2个数据集，默认分出来的数据集名称是train和test
dataset_clean = dataset_reloaded["train"].train_test_split(train_size = 0.7, seed = 42)

# 将原始数据dataset_clean的test set进一步按照50%分割
dataset_temp = dataset_clean["test"].train_test_split(train_size = 0.5, seed = 42)

# data_temp的一半作为验证集，另一半作为测试集
dataset_clean["validation"] = dataset_temp.pop("train")
dataset_clean["test"] = dataset_temp.pop("test")
dataset_clean

from google.colab import drive
drive.mount('/content/drive')

# 下载分词器
# checkpoint = "tabularisai/multilingual-sentiment-analysis"(能跑通), "google-bert/bert-base-chinese"(能跑通)
checkpoint = "hfl/chinese-roberta-wwm-ext"  # 使用专门的中文RoBERTa模型，性能更好
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

# 检查分词器是否需要特殊处理
if not tokenizer.pad_token:
    tokenizer.pad_token = tokenizer.eos_token

# 对于中文RoBERTa模型，确保特殊token配置正确
if not hasattr(tokenizer, 'pad_token') or tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# 将原始数据做分词、标记化（input ids）、padding
def tokenize_function(examples):
    # 对于DeBERTa模型，确保文本长度合适
    return tokenizer(examples["weibo_text"], truncation=True, max_length=512, padding=False)

# 将自定义的tokenize_function应用于rawdatasets. batched = True表示tokenize_function不会一次处理一个样本，而是一次处理一个batch的样本, 这样会大大提高处理速度
tokenized_datasets = dataset_clean.map(tokenize_function, batched = True)

# 创建自定义数据整理器，确保标签类型正确
class RegressionDataCollator(DataCollatorWithPadding):
    def __call__(self, features):
        batch = super().__call__(features)
        # 确保标签是浮点数类型
        if 'labels' in batch:
            batch['labels'] = batch['labels'].float()
        return batch

data_collator = RegressionDataCollator(tokenizer=tokenizer)

dataset_clean = dataset_clean.rename_column(
    "opposite_sex_social_avoidance",
    "labels"
)

# 将标签转换为浮点数，用于回归任务
def convert_labels_to_float(examples):
    examples["labels"] = float(examples["labels"])
    return examples

# 应用标签转换 - 在tokenize之前进行
dataset_clean = dataset_clean.map(convert_labels_to_float, batched=False)

# 强制设置标签特征为浮点数类型
from datasets import Features, Value
float_features = Features({
    'weibo_text': Value('string'),
    'labels': Value('float32')
})

# 重新设置特征类型
for split in ['train', 'validation', 'test']:
    dataset_clean[split] = dataset_clean[split].cast(float_features)

# 创建回归模型 - 输出为1个连续值
model = AutoModelForSequenceClassification.from_pretrained(checkpoint,
                              num_labels = 1,  # 回归任务输出1个值
                              problem_type = "regression",  # 设置为回归任务
                              ignore_mismatched_sizes = True).to(device)

# 对于DeBERTa模型，确保输出层配置正确
if hasattr(model.config, 'classifier_dropout'):
    model.config.classifier_dropout = 0.1

# 定义模型评估指标
def compute_metrics(eval_preds):
    # 回归任务的评估指标
    predictions, labels = eval_preds

    # 确保predictions是一维数组
    if len(predictions.shape) > 1:
        predictions = predictions.squeeze()

    # 计算回归指标
    mse = mean_squared_error(labels, predictions)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(labels, predictions)
    r2 = r2_score(labels, predictions)

    return {
        "mse": mse,
        "rmse": rmse,
        "mae": mae,
        "r2": r2
    }

print(dataset_clean["train"].column_names)
print(dataset_clean["train"][0])

def tokenize_fn(examples):
    return tokenizer(
        examples["weibo_text"],
        truncation=True,
        padding="max_length",
        max_length=128,
    )

dataset_tokenized = dataset_clean.map(tokenize_fn, batched=True)

print(dataset_tokenized["train"].column_names)
print(dataset_tokenized["train"][0])

# 超参数
lr = 5e-5
batch_size = 32
num_epochs = 5

training_args = TrainingArguments(
    output_dir = "test-trainer",
    learning_rate = lr,
    num_train_epochs = num_epochs,
    per_device_train_batch_size = batch_size,
    per_device_eval_batch_size = batch_size,
    report_to = None, # Disable Weights & Biases logging
    logging_strategy = "epoch",
    eval_strategy = "epoch",
    save_strategy = "epoch",
    load_best_model_at_end = True,
    fp16 = False,  # 回归任务建议关闭fp16以避免数值不稳定
    # 回归任务的特定设置
    metric_for_best_model = "rmse",  # 使用RMSE作为最佳模型选择标准
    greater_is_better = False  # RMSE越小越好
)

cols = ["input_ids", "attention_mask", "labels"]
if "token_type_ids" in dataset_tokenized["train"].column_names:
    cols.append("token_type_ids")

dataset_tokenized.set_format(type="torch", columns=cols)



trainer = Trainer(
    # 之前根据checkpoints定义好了的模型
    model = model,
    # 训练模型的参数
    args = training_args,
    # 前面预处理好了的数据
    train_dataset = tokenized_datasets["train"],
    eval_dataset = tokenized_datasets["validation"],
    # 前面定义好的数据整理器，负责动态padding并将数据转为tensors
    data_collator = data_collator,
    tokenizer = tokenizer,
    compute_metrics = compute_metrics
)


# 微调需要有Weights&Bias的账号和API KEY: 57de437dc5e5543be6e4cd4b2744ad404a73d371
# 每跑500次就会报告1次Loss
trainer.train()

import os
from transformers import TrainingArguments, Trainer

# ✅ 彻底禁用 wandb（防止再次弹交互）
os.environ["WANDB_DISABLED"] = "true"

# --------------------
# 超参数
# --------------------
lr = 5e-5
batch_size = 32
num_epochs = 5

# --------------------
# TrainingArguments
# --------------------
training_args = TrainingArguments(
    output_dir="test-trainer",
    learning_rate=lr,
    num_train_epochs=num_epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,

    # ✅ 不上报到 wandb / tensorboard 等
    report_to="none",

    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,

    # 回归任务建议关闭 fp16（你原来写得对）
    fp16=False,

    # 选择最优模型
    metric_for_best_model="rmse",
    greater_is_better=False,
)

# --------------------
# ✅ 确保 Trainer dataloader 里一定包含 labels
# --------------------
cols = ["input_ids", "attention_mask", "labels"]
if "token_type_ids" in dataset_tokenized["train"].column_names:
    cols.append("token_type_ids")

dataset_tokenized.set_format(type="torch", columns=cols)

# --------------------
# Trainer（关键：用 dataset_tokenized，不要用 tokenized_datasets）
# --------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_tokenized["train"],
    eval_dataset=dataset_tokenized["validation"],
    data_collator=data_collator,     # 若你用 DataCollatorWithPadding，可保留
    compute_metrics=compute_metrics, # 你已有的 rmse/pearson 等函数
)

# --------------------
# 开始训练
# --------------------
trainer.train()