# -*- coding: utf-8 -*-
"""社交回避API_GPT_(修改评分标准) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BbcFSoFMa94jY0OLYTudapkM1v2nZRj4
"""

!pip -q install -U openai

import os
from google.colab import userdata
from openai import OpenAI
import openai

print("openai version =", openai.__version__)

DEVDOVE_API_KEY = userdata.get("DEVDOVE_API_KEY")
assert DEVDOVE_API_KEY, "没读到 DEVDOVE_API_KEY：请在 Colab Secrets 里添加"

BASE_URL = "https://api.devdove.site/v1"  # 或 https://api.devdove.top/v1

devdove_client = OpenAI(
    api_key=DEVDOVE_API_KEY,
    base_url=BASE_URL,
)

print("devdove_client type =", type(devdove_client))

MODEL = "gpt-5-mini"

resp = devdove_client.with_options(timeout=30).chat.completions.create(
    model=MODEL,
    messages=[{"role": "user", "content": "只回答数字：1+1="}],
    temperature=0,
    max_tokens=300,  # ✅ 从 10 提到 50 或 100
)

print(resp.choices[0].message.content)
print("finish_reason =", resp.choices[0].finish_reason)

models = devdove_client.with_options(timeout=30).models.list().data
for m in models[:50]:
    print(m.id)

MODEL = "gpt-5"

resp = devdove_client.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user", "content": "只回答数字：1+1="}],
    temperature=0,
    max_tokens=10,
)

print(resp.choices[0].message.content)

"""# 列出可用模型"""

# 这一步能帮你确认 DevDove 侧到底支持哪些模型名
models = devdove_client.models.list()
print("可用模型数量：", len(models.data))
print("前 30 个模型：")
for m in models.data[:30]:
    print("-", m.id)

print(type(devdove_client))

import pandas as pd

INPUT_PATH = "/content/drive/MyDrive/社交回避/weibo_600.csv"
OUTPUT_PATH = "/content/drive/MyDrive/社交回避/pre_weibo_600(gpt-5-mini).csv"

df = pd.read_csv(INPUT_PATH, encoding="gb18030")
assert "weibo_text" in df.columns, f"找不到列 weibo_text，当前列名：{df.columns.tolist()}"

print("✅ 读取成功：", len(df), "条")
df.head()



import json
import time
import random

RUBRIC = """
你是一个心理学评分专家，善于依据评分标准进行任务的评分。

1分： 有理由、有点厌恶
2分： 厌恶所有
3分： 有理由且厌恶
4分： 有生理反应
5分： 极端
请你根据评分标准对以下的内容进行评分（只要一个数字）

【输出格式】
- 只允许输出 JSON，且仅包含一个字段 score，取值为 1~5 的整数：
{"score": 1}
"""

SCORE_SCHEMA = {
    "type": "object",
    "properties": {
        "score": {"type": "integer", "minimum": 1, "maximum": 5}
    },
    "required": ["score"]
}

import json, time, random, re
from typing import List

def score_one(text: str) -> int:
    # 单条也用同一个 RUBRIC，但输出格式改成 {"score":n}
    prompt = (
        RUBRIC.strip()
        + "\n\n【现在请评分这一条】\n"
        + f"微博内容：{text}\n"
        + "只输出 JSON：{\"score\": 1}\n"
    )
    raw = devdove_chat_json(prompt)
    data = json.loads(raw)
    s = int(data["score"])
    if not (1 <= s <= 5):
        raise ValueError("score out of range")
    return s

def score_batch(texts: List[str]) -> List[int]:
    prompt = make_batch_prompt(texts)
    raw = devdove_chat_json(prompt)

    try:
        return parse_batch_json(raw, n=len(texts))
    except Exception:
        # 批量 JSON 解析失败：降级为逐条（更慢但稳）
        scores = []
        for t in texts:
            scores.append(score_one(str(t)))
        return scores


def parse_batch_json(text: str, n: int) -> List[int]:
    data = json.loads(text)
    scores = [None] * n
    for r in data["results"]:
        i = int(r["i"]); s = int(r["score"])
        if 0 <= i < n and 1 <= s <= 5:
            scores[i] = s
    if any(v is None for v in scores):
        raise ValueError("JSON 解析失败：results 未覆盖全部条目或分数越界")
    return [int(x) for x in scores]


import json, time, random, re
from typing import List

# 你说可以慢一点：把间隔加大（比如 0.8~1.5 秒）
MIN_INTERVAL = 1.0
_last_call_t = 0.0

def _sleep_min_interval():
    global _last_call_t
    now = time.monotonic()
    dt = now - _last_call_t
    if dt < MIN_INTERVAL:
        time.sleep((MIN_INTERVAL - dt) + random.random() * 0.2)
    _last_call_t = time.monotonic()

def devdove_chat_json(prompt: str, max_retry: int = 10) -> str:
    last_err = None
    for attempt in range(max_retry):
        try:
            _sleep_min_interval()

            resp = devdove_client.chat.completions.create(
                model=MODEL,
                messages=[
                    {"role": "system", "content": "你是评分程序，只输出 JSON。"},
                    {"role": "user", "content": prompt},
                ],
                temperature=0,
                max_tokens=1800,
                # 如果这个参数不被网关支持，会报 400；你之前能跑说明大概率没问题
                response_format={"type": "json_object"},
            )

            # ——关键：做健壮性检查，避免 choices 为空时报 list index out of range
            if not getattr(resp, "choices", None) or len(resp.choices) == 0:
                raise RuntimeError("empty choices")

            msg = resp.choices[0].message
            content = getattr(msg, "content", None)
            if not content or not str(content).strip():
                raise RuntimeError("empty content")

            # ——关键：确保是 JSON（有时网关会塞点前后缀）
            content = str(content).strip()
            # 兜底：截取第一个 { 到最后一个 } 之间
            if "{" in content and "}" in content:
                content = content[content.find("{"):content.rfind("}")+1]

            # 验证可解析
            json.loads(content)
            return content

        except Exception as e:
            last_err = e

            # 1) 识别常见 429 “Please retry in Xs”
            m = re.search(r"Please retry in ([0-9.]+)s", str(e))
            if m:
                time.sleep(float(m.group(1)) + 0.8 + random.random())
                continue

            # 2) 若是 empty choices/empty content，通常是瞬时异常：稍微等久一点再重试
            if "empty choices" in str(e) or "empty content" in str(e):
                time.sleep(2.0 + random.random() * 1.5)
                continue

            # 3) 其它错误：指数退避
            time.sleep(min(30, (2 ** min(attempt, 6)) + random.random()))

    raise RuntimeError(f"多次重试仍失败：{last_err}")

def score_batch(texts: List[str]) -> List[int]:
    raw = devdove_chat_json(make_batch_prompt(texts))
    return parse_batch_json(raw, n=len(texts))

"""## 尝试一条"""

print("当前 MODEL =", MODEL)

test_text = """这个社会对女性的要求已经很高了，我爸妈对我的要求还高。上学的时候就要好好学习，不准谈恋爱，包括大学也不可以，为啥呢？因为我爸坚持把学习放在第一位，我妈怕我被男人骗；等现在工作了，又突然着急起来了，一个两个的全都在催我谈恋爱。我只想说，你们早干嘛去了？上大学的时候不让我谈，现在刚毕业没几个月，是想让我凭空变一个对象给你们吗！！！当然我自己也有问题，我不清楚我大学时候没谈的原因爸妈影响的比例占多少，但我自己其实也是怕了，初中时候的伤害刻骨铭心+社恐+恐男，现在已经常常不能正常面对一个男性，也不敢跟男性讲话，“好男人太少，周围看见的大部分全都这也不行那也不行”的观点已经根深蒂固很久，从高中就已经慢慢滋长了。所以我现在连一个男性朋友都没有，到哪去给你谈恋爱去！真的无语，别催了别催了。能不能顺其自然。你们焦虑，我只会比你们更焦虑，但痛苦的只有我自己。你们是盼着想让我赶紧结婚吗？别天真了，就我这种是不可能第一段恋情就结婚的，而且谈恋爱就只是人生中的一段经历，并不是为了完成结婚这样的目的才去谈，应该是顺其自然发生的。你们老年人可能不懂这些，毕竟三观不合。"""

import json
import time
import random

def _score_single_text(text: str) -> int:
    """Scores a single text using the DevDove client and the defined RUBRIC."""
    # Construct the prompt for a single text, similar to make_batch_prompt but for one item
    # Note: RUBRIC, MODEL, devdove_client are assumed to be defined globally.
    prompt = (
        RUBRIC.strip()
        + f"\n\n【评分任务：共 1 条】\n"
        + "必须给出 score(1~5)。\n"
        + "只允许输出 JSON，不要输出任何解释、标点或多余文字。\n"
        + "输出格式必须严格为：\n"
        + "{\"score\":1}\n\n"
        + text
    )

    max_retry = 5
    for attempt in range(max_retry):
        try:
            resp = devdove_client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                response_format={"type": "json_object"},
            )
            content = resp.choices[0].message.content
            score_data = json.loads(content)
            score = score_data.get("score")
            if score is not None and 1 <= score <= 5:
                return int(score)
            else:
                raise ValueError(f"Invalid score received: {content}")
        except Exception as e:
            if attempt < max_retry - 1:
                print(f"Retry {attempt + 1}/{max_retry} after error: {e}")
                time.sleep(min(60, (2 ** attempt) + random.random()))
            else:
                raise RuntimeError(f"多次重试仍失败：{e}")

print(_score_single_text(test_text))

"""# 批量评分"""

assert "RUBRIC" in globals(), "你还没定义 RUBRIC：请先运行你文件里那段 RUBRIC 的 cell"

import json, time, random, re
from typing import List

# 你说可以慢一点：这里控制请求频率
MIN_INTERVAL = 1.2
_last_call_t = 0.0

def _sleep_min_interval():
    global _last_call_t
    now = time.monotonic()
    dt = now - _last_call_t
    if dt < MIN_INTERVAL:
        time.sleep((MIN_INTERVAL - dt) + random.random() * 0.2)
    _last_call_t = time.monotonic()

def _extract_json_obj(s: str) -> str:
    s = (s or "").strip()
    if "{" in s and "}" in s:
        s = s[s.find("{"): s.rfind("}") + 1]
    return s

def _client_with_timeout(timeout_s: float):
    # openai>=1.x 支持 with_options；不支持就退回原 client
    try:
        return devdove_client.with_options(timeout=timeout_s)
    except Exception:
        return devdove_client

def call_json(prompt: str, max_retry: int = 8, timeout_s: float = 60.0) -> str:
    """
    返回：一个可 json.loads 的 JSON 字符串
    """
    last_err = None
    cli = _client_with_timeout(timeout_s)

    for attempt in range(max_retry):
        try:
            _sleep_min_interval()
            resp = cli.chat.completions.create(
                model=MODEL,
                messages=[
                    {"role": "system", "content": "你是评分程序，只输出JSON，不要解释。"},
                    {"role": "user", "content": prompt},
                ],
                temperature=0,
                max_tokens=1800,
            )

            choices = getattr(resp, "choices", None) or []
            if len(choices) == 0:
                raise RuntimeError("empty choices")

            content = getattr(choices[0].message, "content", "")
            content = _extract_json_obj(content)
            json.loads(content)  # 验证
            return content

        except Exception as e:
            last_err = e
            # 429 常见提示：Please retry in Xs
            m = re.search(r"Please retry in ([0-9.]+)s", str(e))
            if m:
                time.sleep(float(m.group(1)) + 0.8 + random.random())
            else:
                time.sleep(min(15, (2 ** min(attempt, 5)) + random.random()))

    raise RuntimeError(f"call_json 重试失败：{last_err}")

def score_one(text: str) -> int:
    prompt = (
        RUBRIC.strip()
        + "\n\n【现在请评分这一条】\n"
        + f"微博内容：{text}\n"
        + "只输出JSON：{\"score\": 1}\n"
    )
    raw = call_json(prompt)
    d = json.loads(raw)
    s = int(d["score"])
    if not (1 <= s <= 5):
        raise ValueError("score out of range")
    return s

def score_batch(texts: List[str]) -> List[int]:
    n = len(texts)
    numbered = "\n".join([f"{i}. {t}" for i, t in enumerate(texts)])
    prompt = (
        RUBRIC.strip()
        + "\n\n【批量评分】\n"
        + "对每条给出 score(1~5)，并保留序号 i。\n"
        + "只输出严格JSON：{\"results\":[{\"i\":0,\"score\":1},{\"i\":1,\"score\":3}]}\n\n"
        + numbered
    )

    try:
        raw = call_json(prompt)
        obj = json.loads(raw)
        results = obj["results"]

        scores = [None] * n
        for r in results:
            i = int(r["i"]); s = int(r["score"])
            if 0 <= i < n and 1 <= s <= 5:
                scores[i] = s

        if any(v is None for v in scores):
            raise ValueError("batch results 不完整")

        return [int(x) for x in scores]

    except Exception:
        # 批量失败就逐条（慢一点但稳）
        return [score_one(t) for t in texts]

from tqdm.notebook import tqdm
import os
import pandas as pd

TEXT_COL = "weibo_text"

# 断点续跑：如果已有输出，优先加载（不改你之前读 df 的代码，但这里更稳）
if os.path.exists(OUTPUT_PATH):
    try:
        df_existing = pd.read_csv(OUTPUT_PATH, encoding="utf-8")
        if len(df_existing) == len(df) and "score" in df_existing.columns:
            df = df_existing
            print("✅ 检测到已有输出文件，将续跑未完成部分。")
    except Exception:
        pass

if "score" not in df.columns:
    df["score"] = pd.NA

pending_idx = [idx for idx in df.index if pd.isna(df.at[idx, "score"])]
print("待评分条数：", len(pending_idx))

BATCH_SIZE = 10   # 建议先 10；稳定后你再调到 15/20
SAVE_EVERY = 5    # 每 5 个 batch 保存一次

for start in tqdm(range(0, len(pending_idx), BATCH_SIZE), desc="批量评分", unit="batch"):
    idxs = pending_idx[start:start + BATCH_SIZE]
    texts = [str(df.at[i, TEXT_COL]) for i in idxs]

    scores = score_batch(texts)

    for i, s in zip(idxs, scores):
        df.at[i, "score"] = int(s)

    if (start // BATCH_SIZE + 1) % SAVE_EVERY == 0:
        df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8")
        print(f"💾 已保存进度 -> {OUTPUT_PATH}")

df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8")
print("✅ 全部完成 ->", OUTPUT_PATH)

"""# 计算指标"""

!pip -q install -U scikit-learn scipy pandas

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, cohen_kappa_score
from scipy.stats import spearmanr

PATH = "/content/GPT-5-mini_600.csv"
TRUE_COL = "true_score"
PRED_COL = "pre_score"

def read_csv_with_fallback(path: str) -> pd.DataFrame:
    encodings = ["utf-8", "utf-8-sig", "gb18030", "gbk", "latin1"]
    last_err = None
    for enc in encodings:
        try:
            df = pd.read_csv(path, encoding=enc)
            print(f"✅ 成功读取：encoding = {enc}")
            return df
        except Exception as e:
            last_err = e
    raise last_err

# 1) 读取
df = read_csv_with_fallback(PATH)

# 2) 校验列
assert TRUE_COL in df.columns, f"找不到列 {TRUE_COL}，当前列：{df.columns.tolist()}"
assert PRED_COL in df.columns, f"找不到列 {PRED_COL}，当前列：{df.columns.tolist()}"

# 3) 清理与转换
d = df[[TRUE_COL, PRED_COL]].copy()
d[TRUE_COL] = pd.to_numeric(d[TRUE_COL], errors="coerce")
d[PRED_COL] = pd.to_numeric(d[PRED_COL], errors="coerce")
d = d.dropna(subset=[TRUE_COL, PRED_COL])

y_true = d[TRUE_COL].to_numpy()
y_pred = d[PRED_COL].to_numpy()

print("\n文件：", PATH)
print("有效样本数 N =", len(d))

# 4) 回归指标：R² / MSE / RMSE
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_true, y_pred)

print("\n=== 回归指标 ===")
print("R²   =", r2)
print("MSE  =", mse)
print("RMSE =", rmse)

# 5) 推荐一起报告（更贴合 1~5 有序评分）
mae = mean_absolute_error(y_true, y_pred)
rho, p = spearmanr(y_true, y_pred)

print("\n=== 有序评分推荐指标 ===")
print("MAE =", mae)
print("Spearman rho =", rho, "| p =", p)

# 6) 二次加权 Kappa（把分数四舍五入到 1~5）
yt = np.clip(np.rint(y_true), 1, 5).astype(int)
yp = np.clip(np.rint(y_pred), 1, 5).astype(int)
qwk = cohen_kappa_score(yt, yp, weights="quadratic")

print("\n=== 一致性指标（推荐） ===")
print("Quadratic Weighted Kappa =", qwk)

from google.colab import drive
drive.mount('/content/drive')